
services:
  keycloak-mysql:
    container_name: keycloak-mysql
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_USER: admin
      MYSQL_PASSWORD: 12345
      MYSQL_DATABASE: user

    ports:
      - "3309:3309"

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    container_name: keycloak
    command: ["start-dev","--import-realm"]
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: MYSQL
      DB_DATABASE: user
      DB_USER: admin
      DB_PASSWORD: 12345
      KEYCLOAK_ADMIN: ADMİN
      KEYCLOAK_ADMIN_PASSWORD: 12345

    ports:
      - "8181:8080"
    depends_on:
      - keycloak-mysql

