services:
  mongo:
    image: mongo
    container_name: mongoc
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 12345
    networks:
      - mongodb_network

  mongo-express:
    image: mongo-express
    container_name: mongo-expressc
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=12345
      - ME_CONFIG_MONGODB_SERVER=mongoc
    depends_on:
      - mongo
    networks:
      - mongodb_network

networks:
  mongodb_network:
    name: mongodb_network
